### ISSUE TITLE
"Back" button not always useful

### ISSUE THREAD

**Issue by Endogen** [bingbinglee/idena-chrome-extension#1]
If you open a transaction directly (for example through a link) then the "Back" button doesn't work. I think it would be great if it could open the address details again (`https://scan.idena.io/address?address=<address>`)
![image](https://user-images.githubusercontent.com/226475/80569923-298a9a00-89fa-11ea-97f7-fb467ceee7e9.png)

**Comment by bingbinglee** [comment]
Fixed in https://github.com/bingbinglee/idena-chrome-extension/commit/9c15c45ec625ce37e8feed420983fc42c5f5a8ec Should be available in v0.1.9
