### ISSUE TITLE
Uptrend shows as `+-`

### ISSUE THREAD

**Issue by Endogen** [bingbinglee/idena-chrome-extension#2]
If price goes up, it should display a `+` but it in some cases displays `+-`
![image](https://user-images.githubusercontent.com/226475/80576474-8b043600-8a05-11ea-9304-73205f8f373b.png)

**Comment by bingbinglee** [comment]
Is this what you see now too? I am wondering if it's related to local browser settings which I have not considered. For example: showing commas instead of . for you locally. 

Let me know. Not able to reproduce here.

**Comment by bingbinglee** [comment]
Solved in this https://github.com/bingbinglee/idena-chrome-extension/commit/576de914f5ef29f2834d39244d41346d41b4e64d. Will close once v0.1.10 releases and I can circle back to verify if it's closed on your end. Leaving issue till then.

**Comment by bingbinglee** [comment]
This should be fixed now. V0.1.10 is live. @Endogen let me know if it has been fixed on your side and I will close it.
